Correction error exit in case

diff --git a/testframework/bin/runTTF b/testframework/bin/runTTF
--- a/testframework/bin/runTTF
+++ b/testframework/bin/runTTF
@@ -56,9 +56,9 @@ function interruptSignalMain {
 
 trap interruptSignalMain SIGINT
 
-# Function errorExit
+# Function errorTrapFunc
 #	global error exit function - prints the caller stack
-function errorExit {
+function errorTrapFunc {
 	echo -e "\033[31mERROR: $FUNCNAME ***************"
 	local -i i=0;
 	while caller $i; do
@@ -67,7 +67,7 @@ function errorExit {
 	echo -e "************************************************\033[0m"
 }
 
-trap errorExit ERR
+trap errorTrapFunc ERR
 #trap -p
 
 #-----------------------------------------------------
